# Generated by Django 4.1 on 2022-08-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaEquipe', models.CharField(default='', max_length=240)),
                ('equipeAtual', models.CharField(default='', max_length=240)),
                ('quantidadeIntegrantes', models.IntegerField()),
                ('seConhecem', models.BooleanField(default=False)),
                ('etapaFinalizada', models.CharField(blank=True, default='', max_length=35)),
                ('definidor', models.CharField(blank=True, default='', max_length=35)),
                ('facilitador', models.CharField(blank=True, default='', max_length=35)),
                ('observador', models.CharField(blank=True, default='', max_length=35)),
                ('entrevistador', models.CharField(blank=True, default='', max_length=35)),
                ('scrumMaster', models.CharField(blank=True, default='', max_length=35)),
                ('linkRetrospectiva1', models.CharField(blank=True, default='', max_length=240)),
                ('linkRetrospectiva2', models.CharField(blank=True, default='', max_length=240)),
                ('linkRetrospectiva3', models.CharField(blank=True, default='', max_length=240)),
                ('linkRetrospectiva4', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
