# Generated by Django 2.2.15 on 2022-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquipe', models.CharField(max_length=240, unique=True)),
                ('quantidadeIntegrantes', models.IntegerField()),
                ('seConhecem', models.BooleanField(default=False)),
                ('etapaFinalizada', models.CharField(max_length=35)),
                ('definidor', models.CharField(max_length=35)),
                ('facilitador', models.CharField(max_length=35)),
                ('responsavelTempo', models.CharField(max_length=35)),
                ('linkRetrospectiva1', models.CharField(max_length=240)),
                ('linkRetrospectiva2', models.CharField(max_length=240)),
                ('linkRetrospectiva3', models.CharField(max_length=240)),
                ('linkRetrospectiva4', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
