# Generated by Django 2.2.15 on 2022-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='equipeAtual',
            field=models.CharField(default=models.CharField(default='', max_length=240, unique=True), max_length=240),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='etapaFinalizada',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='nomeEquipe',
            field=models.CharField(default='', max_length=240, unique=True),
        ),
    ]
