# Generated by Django 2.2.15 on 2022-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220821_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipes',
            old_name='nomeEquipe',
            new_name='nomeDaEquipe',
        ),
        migrations.AlterField(
            model_name='equipes',
            name='equipeAtual',
            field=models.CharField(max_length=240),
        ),
    ]
