# Generated by Django 2.2.15 on 2022-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220821_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='nomeDaEquipe',
            field=models.CharField(default='', max_length=240),
        ),
    ]
