# Generated by Django 4.1 on 2022-11-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_equipes_nomedaequipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='linkRetrospectiva1',
        ),
        migrations.RemoveField(
            model_name='equipes',
            name='linkRetrospectiva2',
        ),
        migrations.RemoveField(
            model_name='equipes',
            name='linkRetrospectiva3',
        ),
        migrations.RemoveField(
            model_name='equipes',
            name='linkRetrospectiva4',
        ),
    ]
