# Generated by Django 4.1 on 2022-11-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_equipes_atividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='seConhecem',
        ),
    ]
