# Generated by Django 2.2.15 on 2022-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220821_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='definidor',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='facilitador',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='responsavelTempo',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
