# Generated by Django 4.1 on 2022-11-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_equipes_seconhecem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipes',
            old_name='criado_em',
            new_name='criadoEm',
        ),
    ]
