# Generated by Django 2.2.15 on 2022-08-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20220821_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
