# Generated by Django 2.2.15 on 2022-08-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_equipes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='owner',
        ),
    ]
