# Generated by Django 4.1 on 2022-08-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_equipes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='equipeAtual',
        ),
    ]
