# Generated by Django 4.1 on 2022-08-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_equipes_equipeatual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipes',
            old_name='responsavelTempo',
            new_name='entrevistador',
        ),
        migrations.AddField(
            model_name='equipes',
            name='observador',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='equipes',
            name='scrumMaster',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
