# Generated by Django 4.1 on 2022-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_responsaveltempo_equipes_entrevistador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipes',
            name='nomeDaEquipe',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False),
        ),
    ]
