# Generated by Django 4.1 on 2022-08-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_equipes_equipe_id_equipes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipes',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipes',
            name='nomeDaEquipe',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False),
        ),
    ]
