# Generated by Django 4.1 on 2022-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_equipes_id_alter_equipes_nomedaequipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='nomeDaEquipe',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False, unique=True),
        ),
    ]
