# Generated by Django 4.1 on 2022-11-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_remove_equipes_linkretrospectiva1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesEtapa',
            fields=[
                ('id_atividade', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('tituloAtividade', models.CharField(blank=True, default='', max_length=500)),
                ('tipo', models.CharField(blank=True, default='', max_length=60)),
                ('descricao', models.CharField(blank=True, default='', max_length=3800)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('descricaoLink', models.CharField(blank=True, default='', max_length=500)),
                ('descricaoTempo', models.CharField(blank=True, default='', max_length=500)),
                ('tempoEstimado', models.IntegerField(blank=True, default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacaoExtra', models.CharField(blank=True, default='', max_length=240)),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_atividades.atividadesetapa')),
                ('id_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipes')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nomeEtapa', models.CharField(blank=True, default='', max_length=60)),
                ('proxima', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximaEtapa', to='api_atividades.etapa')),
            ],
        ),
        migrations.AddField(
            model_name='atividadesetapa',
            name='etapaPertencente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapaPertencente', to='api_atividades.etapa'),
        ),
        migrations.AddField(
            model_name='atividadesetapa',
            name='proxima',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximaAtividade', to='api_atividades.atividadesetapa'),
        ),
    ]
