# Generated by Django 4.1 on 2022-11-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='proxima',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximaEtapa', to='api_atividades.etapa'),
        ),
    ]
