# Generated by Django 4.1 on 2022-11-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_atividades', '0003_remove_atividadesetapa_descricaotempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesetapa',
            name='proxima',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximaAtividade', to='api_atividades.atividadesetapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='proxima',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximaEtapa', to='api_atividades.etapa'),
        ),
    ]
