# Generated by Django 4.1 on 2022-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_atividades', '0004_alter_atividadesetapa_proxima_alter_etapa_proxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesetapa',
            name='id_atividade',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id_etapa',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
