# Generated by Django 4.1 on 2022-11-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_atividades', '0008_alter_historicoatividades_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoatividades',
            unique_together=set(),
        ),
    ]
