# Generated by Django 4.1 on 2022-11-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_equipes_seconhecem'),
        ('api_atividades', '0011_alter_historicoatividades_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historicoatividades',
            unique_together={('id_atividade', 'id_equipe')},
        ),
    ]
